# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.version: '%env(APP_VERSION)%'
    app.name: '%env(APP_NAME)%'
    app.maintenance: '%env(APP_MAINTENANCE)%'
    app.memcached.host: '%env(APP_MEMCACHED_HOST)%'
    app.memcached.port: '%env(APP_MEMCACHED_PORT)%'
    app.memcached.timeout: '%env(APP_MEMCACHED_TIMEOUT)%'
    app.kevacoin.protocol: '%env(APP_KEVACOIN_PROTOCOL)%'
    app.kevacoin.host: '%env(APP_KEVACOIN_HOST)%'
    app.kevacoin.port: '%env(APP_KEVACOIN_PORT)%'
    app.kevacoin.username: '%env(APP_KEVACOIN_USERNAME)%'
    app.kevacoin.password: '%env(APP_KEVACOIN_PASSWORD)%'
    app.kevacoin.withdraw.profit.address: '%env(APP_KEVACOIN_WITHDRAW_PROFIT_ADDRESS)%'
    app.kevacoin.withdraw.balance.min.kva: '%env(APP_KEVACOIN_WITHDRAW_BALANCE_MIN_KVA)%'
    app.kevacoin.withdraw.balance.max.kva: '%env(APP_KEVACOIN_WITHDRAW_BALANCE_MAX_KVA)%'
    app.kevacoin.room.namespaces.pinned: '%env(APP_KEVACOIN_ROOM_NAMESPACES_PINNED)%'
    app.kevacoin.room.namespaces.readonly: '%env(APP_KEVACOIN_ROOM_NAMESPACES_READONLY)%'
    app.kevacoin.room.namespace.default: '%env(APP_KEVACOIN_ROOM_NAMESPACE_DEFAULT)%'
    app.kevacoin.boost.address: '%env(APP_KEVACOIN_BOOST_ADDRESS)%'
    app.kevacoin.explorer.url: '%env(APP_KEVACOIN_EXPLORER_URL)%'
    app.kevacoin.mine.pool.url: '%env(APP_KEVACOIN_MINE_POOL_URL)%'
    app.kevacoin.mine.solo.url: '%env(APP_KEVACOIN_MINE_SOLO_URL)%'
    app.session.default.timeout: '%env(APP_SESSION_DEFAULT_TIMEOUT)%'
    app.session.online.timeout: '%env(APP_SESSION_ONLINE_TIMEOUT)%'
    app.add.user.name.regex: '%env(APP_ADD_USER_NAME_REGEX)%'
    app.add.user.name.blacklist: '%env(APP_ADD_USER_NAME_BLACKLIST)%'
    app.add.user.remote.ip.delay: '%env(APP_ADD_USER_REMOTE_IP_DELAY)%'
    app.add.room.remote.ip.regex: '%env(APP_ADD_ROOM_REMOTE_IP_REGEX)%'
    app.add.room.remote.ip.delay: '%env(APP_ADD_ROOM_REMOTE_IP_DELAY)%'
    app.add.room.remote.ip.denied: '%env(APP_ADD_ROOM_REMOTE_IP_DENIED)%'
    app.add.room.keva.ns.value.regex: '%env(APP_ADD_ROOM_KEVA_NS_VALUE_REGEX)%'
    app.add.post.remote.ip.regex: '%env(APP_ADD_POST_REMOTE_IP_REGEX)%'
    app.add.post.remote.ip.delay: '%env(APP_ADD_POST_REMOTE_IP_DELAY)%'
    app.add.post.remote.ip.denied: '%env(APP_ADD_POST_REMOTE_IP_DENIED)%'
    app.add.post.key.regex: '%env(APP_ADD_POST_KEY_REGEX)%'
    app.add.post.value.regex: '%env(APP_ADD_POST_VALUE_REGEX)%'
    app.add.post.cost.kva: '%env(APP_ADD_POST_COST_KVA)%'
    app.add.room.cost.kva: '%env(APP_ADD_ROOM_COST_KVA)%'
    app.add.user.cost.kva: '%env(APP_ADD_USER_COST_KVA)%'
    app.pool.confirmations: '%env(APP_POOL_CONFIRMATIONS)%'
    app.pool.timeout: '%env(APP_POOL_TIMEOUT)%'
    app.moderator.remote.ip: '%env(APP_MODERATOR_REMOTE_IP)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Twig\AppExtension:
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension}