# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.version: '%env(APP_VERSION)%'
    app.name: '%env(APP_NAME)%'
    app.memcached.host: '%env(APP_MEMCACHED_HOST)%'
    app.memcached.port: '%env(APP_MEMCACHED_PORT)%'
    app.memcached.timeout: '%env(APP_MEMCACHED_TIMEOUT)%'
    app.kevacoin.protocol: '%env(APP_KEVACOIN_PROTOCOL)%'
    app.kevacoin.host: '%env(APP_KEVACOIN_HOST)%'
    app.kevacoin.port: '%env(APP_KEVACOIN_PORT)%'
    app.kevacoin.username: '%env(APP_KEVACOIN_USERNAME)%'
    app.kevacoin.password: '%env(APP_KEVACOIN_PASSWORD)%'
    app.kevacoin.room.namespaces: '%env(APP_KEVACOIN_ROOM_NAMESPACES)%'
    app.kevacoin.room.namespaces.readonly: '%env(APP_KEVACOIN_ROOM_NAMESPACES_READONLY)%'
    app.kevacoin.room.namespace.default: '%env(APP_KEVACOIN_ROOM_NAMESPACE_DEFAULT)%'
    app.kevacoin.room.namespace.external: '%env(APP_KEVACOIN_ROOM_NAMESPACE_EXTERNAL)%'
    app.kevacoin.mine.address: '%env(APP_KEVACOIN_MINE_ADDRESS)%'
    app.kevacoin.mine.pool.url: '%env(APP_KEVACOIN_MINE_POOL_URL)%'
    app.kevacoin.mine.solo.url: '%env(APP_KEVACOIN_MINE_SOLO_URL)%'
    app.add.room.remote.ip.regex: '%env(APP_ADD_ROOM_REMOTE_IP_REGEX)%'
    app.add.post.remote.ip.regex: '%env(APP_ADD_POST_REMOTE_IP_REGEX)%'
    app.add.post.remote.ip.delay: '%env(APP_ADD_POST_REMOTE_IP_DELAY)%'
    app.add.post.remote.ip.moderators: '%env(APP_ADD_POST_REMOTE_IP_MODERATORS)%'
    app.add.post.remote.ip.denied: '%env(APP_ADD_POST_REMOTE_IP_DENIED)%'
    app.add.post.value.regex: '%env(APP_ADD_POST_VALUE_REGEX)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Twig\AppExtension:
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension}